sudo: false
language: node_js
dist: trusty
notifications:
  email: false
node_js:
- '8'
- '9'
services:
- mongodb
- redis-server
env:
  matrix:
  - NODE_ENV=ci PORT=3000
  global:
  - secure: Un9Q1uO5yq+lU1JgV+kcRakjBAhkrRe6AjdSKuqAPAfoqG9vBFjGEsrP0vugC6lW6PnLxNOFDiVDZjf4r8f/J0yYZjjUEn+LmCVcvtZc3vZmFN2EsyE5mD6EGA70Y+pgBR4X5pZLrfn05I2h6KQ86Y5R9agxHcQedJTf6xCG5YUrtXw4k3CULDP1Y1Zd9TIwLqTM7ocvkyuXHuTL7ZfpoYJa3JvcxfIGS7crkvkARnQybtFfysslkFokKHvo8qvdRoaqivSgmYJEbKwAVkYW8LfUsXIn6L2jLpeaAngREhhULEdB68SvBYFdj71vOnLQC53zZhM1b7UTjAQIAgJt2CYX3fFgsURlYyX9DSSxTAJbex4A5uOeHPOUR0TVIgoyyQmU3D4vIM76XissRK4GyVODZzkYnb0N5h1CxfcEqIG9MYq/eDg0t9JwBLlOeR8OETnv6qHJgUQjr3QhO89N8l3/bGp35Q4jd9gtAWOjWOtG74TjfbfdfKvJkgKq5E9YGdwOPFl/cks6qR9COzznz2piGag6/fyu+HD+63geiCqbeP4id3F0PSjTgOjHKzKGWRo6enOlrd5u0eMQJMfxew9MlE/wgZvSki+Jupt+qQ1hY4tJk3Njy17sBrDTP9kRgxJtgGMwfAPcfAzSkiOHWgHIfs427SC4X6PEA72Cmy4=
  - secure: VQh3uC9kQGWQY3xMOSwtJc+1O/+7We/DJJULJwrMKOEUn79adELdZt1aFbo4oheldES087yU4yjeQT1cIJsnviGB/Bypz4H7rJKan2q2UVhNICZh4JnWXLTJUWaJiaGR5Rz39wY0WScCl84SjqPdnmu/1tcSvZzFc+oYVqxQrj/XDsBsL62ivnpYNxkLolR86Rc++EvGEig2/Q7X9+t4GQDBM7j6JFkC98iemRvPGkLv/tSZvDikdep3gxCbKWe54UvXe/6lcRuG+fnoTUJSdfonoFmNou5o7CR8Bmq2pKJNWvsiC1dTH6mdCOVfTaz/yKtN6opSuCuqARDDd5J7zTLzIBgjXVGL13lGRS8ir7u2AdF77v00vGZioJiUBgC4q373ixYMHLFqpvVayrky2Zreg2WtABCEE6TNtGOv/SgWalAcjmgzFBZTL4+awGgI1jgfn4Vu5jRaf6Lr6iYsImW0nDrZ0l0hSQrzJJvn2/HslqYXVlsGdoIah1AjcDYUhLUD5jrY8zTGmznowPEOoo8+qJjIMxeuG8YKMei1JVsu4ZQT2sr4fWCg2gczPZhARNQKYeyuRpeDrzlLuQqvhoMM9mNYZn1aL+AI27EaQLvy23Fo3Zkd+SFQnNUxiC0E1OC1r6mRYQGFD1QxQ2b9DZOnGY0rW6RL4yzM79nDGo0=
  - secure: rB59s2dlm466NvdlZ3Xdx9OL0hI+F7LRFa/4brJ06eA5BEVXuTnbVO8FndaQ9RfZOdzbxz5WvR/4Iz92ltRZxWhmQ+r3NVullsgk3z/u1vVcKPyI5Am5jv05u/m6M2BxV2/87MALH0dIXicFliYuskoCwjpEI7+xpJCL54QxFyMa+lzHOM7m4zb7Crabd6Fiysff3wdmZ4hSJbGIwpumK2Z01L7aNfpa+6k5+O+ZRwfEy6g8Uxt4Gh0clOhJ7o9cCbGaRfrwbe9lN4nmquhfQ6zgZ8sNbyfwSRPI1Qbd8YAvJBF77pYNi2iWOQNBC7t/i3lFzUUAXljF+rGP/PG4YAxhK4OSjiwHF8ySJREZBdCAHYQHPlEjzMfP436GbsDMgsqiO2YF57fLRkglREjlLoj2rbOE6LuZcYl/AH7ht9229idRdSLWWGevaxZV7+Ni3dbCgW1U7VFtXJn4+9vfw6cf7j/Kq5PSB//ODMD4o6Dp3vaI8Ko1WzV9VPaD7wpSMFEZrAajx/WiUjAGdph/rdiyuVjZICoTgf4BYh5kbL7N/eKhWreD6ns340kNwXuS3SgUZEYZJqETWmQh+5pcvvWLNGYI/eFe3w4egpvqRsOhjUqTLSK8On+Ht17+tsud4VAkk5OI+4a9oZscH/fd6xALv4DfaCD9fLTcabUMOLk=
  - secure: inXu6XNcPgNgfbOxbLucRMqqzhjOaCl1vtfBK0j7jG/Tgc326gNx8XlR3ygCm6TiN5wMP3ZdKu92m30JjhFyvWfTkY+tBzKzxQvTnrnZ0fbhuDvodp4h7utEGHMOKP6jw/ywomNlNGZvqL6JVHrwoLo3/h4CxcfjVMPtMdDx3QN4Wsgt3EWwYQrHQyW1C2kEzU5H7bpiUMbiF+uZZotVoCInfBwz3+xftEO3jwfNLaJ+mrqFn/DkdyVqk7tmNIy1oZm7HF6vzma+0ESpohAaoLHKO76+ipbrGA0H6/znnU0NCji6TX9Aar2LimRhJabzCjhoQHyPuXiICAh15js8SCO6rCRdQqsrlNdCLk+TfiWKe0+nCVSN6jaXAlncSInCxkZCQG+hg7F2oz93ToGdiyAEL2G1CHNgIdRJHnA9Nd7f8PJeW3SGPRxXbQlRsbri62N9AD+XpzFGQa8hXPt8kxVyQ9LeOYs+snhZm2DRg2I6xo5yjAPWPAim4mx2oG/kyC2SMB6/0rD/g89nwr/n2OHaBgqF7BJo3OC1foNZ3BUKee8HUJ9FYIs7qHsW/nDT/8SJX8kN/PNGLLqOYI66ODGimi9dAWr4LDy1f9/fHqy6cbHdTRQ/GrDYa4kEdiII5VwNOw5/zQS+UT0vOjErWQ00BShViAooPwhQTForv5Y=
cache:
  directories:
  - node_modules
  - client/node_modules
before_install:
- npm install -g npm@latest
install:
- npm install
- npm run build
script:
- nohup npm start &
- sleep 3
- npm run test
