sudo: false

language: node_js

dist: trusty

notifications:
  email: false

# async-await implementation in node v7.6+
node_js:
  - "8"
  - "9"

services:
  - mongodb
  - redis-server

env:
  - NODE_ENV=ci PORT=3000

cache:
  directories:
  - node_modules
  - client/node_modules

before_install:
  - npm install -g npm@latest

install:
  - npm install
  - npm run build

script:
  - nohup npm start &
  - sleep 3
  - npm run test

